[package]
name = "which-linker-fast"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.dev]
debug = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = "z"

debug = false
strip = true
